### ISSUE TITLE
ERROR in Django 1.11

### ISSUE THREAD

**Issue by djsan15** [gitaarik/django-admin-relation-links#4]
I am getting an error when I try to open admin change page:
````
super() takes at least 1 argument (0 given)

"site-packages/django_admin_relation_links/options.py" in get_fields
          fields = list(super().get_fields(request, obj=None))
````

**Comment by jamiecollinson** [comment]
Just hit the same issue - I presume you're also using Python 2? The `super()` call doesn't include the class which is why it's not working.

I guess that means the library author isn't supporting Python 2. It would work with both 2 and 3 to include the class as a parameter, but there may be other bits of code which aren't Python 2 compatible as well.

**Comment by gitaarik** [comment]
Sorry for the late reply, I just found out I didn't receive notifications for this repository. Feel free to do a pull request to support Python 2.
